name: Deploy Fulusku Service

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fulusku-service:latest
            docker stop fulusku-service || true && docker rm fulusku-service || true
            docker run -d \
              --name fulusku-service \
              --network fulusku_default \
              --env-file /home/${{ secrets.VPS_USER }}/fulusku/.env \
              -p 8080:8080 \
              ${{ secrets.DOCKERHUB_USERNAME }}/fulusku-service:latest
